package com.wallshare.app.wallpaper

import io.github.jan.supabase.SupabaseClient
import io.github.jan.supabase.auth.auth
import io.github.jan.supabase.postgrest.postgrest
import io.github.jan.supabase.storage.storage
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import java.util.UUID

/**
 * Owns every direct Supabase call for sending and applying wallpapers.
 *
 * IMPORTANT: the `wallpapers` bucket is PRIVATE (Step 2) - there is no public
 * URL to hand out. Downloads go through downloadAuthenticated(), which is
 * subject to the same storage RLS policies as everything else (sender or
 * receiver of the matching wallpaper_requests row only).
 *
 * The request id is generated by sendWallpaper() BEFORE upload, not after -
 * send_wallpaper() (Step 2) validates that the storage path is exactly
 * {sender_id}/{request_id}.<ext>, so the id has to exist before the file is
 * written, not be assigned to an already-uploaded file.
 *
 * wallpaper_requests has no client INSERT policy at all, so creation always
 * goes through the send_wallpaper() RPC - never a raw insert.
 */
class WallpaperRepository(private val supabase: SupabaseClient) {

    private fun currentUserId(): String =
        supabase.auth.currentUserOrNull()?.id
            ?: throw IllegalStateException("WallpaperRepository used with no active session")

    /**
     * Uploads the image, then creates the wallpaper request via
     * send_wallpaper() (Step 2), which atomically checks friendship,
     * supersedes any existing pending request for this receiver, and
     * inserts the new row - all server-side.
     */
    suspend fun sendWallpaper(
        receiverId: String,
        imageBytes: ByteArray,
        extension: String,
        target: WallpaperTarget,
    ): Result<Unit> {
        return try {
            val senderId = currentUserId()
            val requestId = UUID.randomUUID().toString()
            val path = "$senderId/$requestId.$extension"

            supabase.storage.from("wallpapers").upload(path, imageBytes)

            supabase.postgrest.rpc(
                "send_wallpaper",
                buildJsonObject {
                    put("p_request_id", requestId)
                    put("p_receiver_id", receiverId)
                    put("p_image_path", path)
                    put("p_target", target.name)
                },
            )
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    /**
     * Re-fetches a request by id, requiring it to still be PENDING and
     * addressed to the given receiver. Used by WallpaperWorker to verify
     * the FCM payload against real database state - the payload is a hint,
     * never trusted directly (see WallShareMessagingService).
     */
    /**
     * Re-fetches a request by id, requiring it to still be PENDING or PROCESSING
     * and addressed to the given receiver. Used by WallpaperWorker to verify
     * the FCM payload against real database state, and recover interrupted jobs.
     */
    suspend fun fetchActiveRequest(requestId: String, receiverId: String): WallpaperRequestRow? {
        return supabase.postgrest.from("wallpaper_requests")
            .select {
                filter {
                    eq("id", requestId)
                    eq("receiver_id", receiverId)
                    isIn("status", listOf("PENDING", "PROCESSING"))
                }
            }
            .decodeSingleOrNull<WallpaperRequestRow>()
    }

    /**
     * Fetches all requests that are PENDING or PROCESSING for the current user.
     * Used at startup to reconcile any missed FCM push notifications.
     */
    suspend fun getPendingRequests(): List<WallpaperRequestRow> {
        val receiverId = currentUserId()
        return supabase.postgrest.from("wallpaper_requests")
            .select {
                filter {
                    eq("receiver_id", receiverId)
                    isIn("status", listOf("PENDING", "PROCESSING"))
                }
            }
            .decodeList<WallpaperRequestRow>()
    }

    /** Downloads the actual image bytes through the authenticated (private-bucket) API. */
    suspend fun downloadImage(imagePath: String): ByteArray {
        return supabase.storage.from("wallpapers").downloadAuthenticated(imagePath)
    }

    /**
     * Updates status. RLS only allows the receiver to do this at all, and
     * the Step 2 trigger only allows legal transitions
     * (PENDING -> PROCESSING -> COMPLETED/FAILED) - an illegal transition
     * attempt here will simply fail, which the worker treats as an error.
     */
    suspend fun updateStatus(requestId: String, status: String): Result<Unit> {
        return try {
            supabase.postgrest.from("wallpaper_requests")
                .update({ set("status", status) }) {
                    filter { eq("id", requestId) }
                }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}